spring:
  datasource:
    # ? ??? ? DB ??? ??? ??? ????? ??? ?? ???
    url: jdbc:mysql://localhost:3306/jpa
    username: root
    password: Gjwldud0343!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update #create(?? ??? ??? ??, ??? ?? x), create-drop(create? ???? ?? ?? x)
    show-sql: true #ORM?? ??? ??? ??? ???
    properties:
      hibernate:
        format-sql: true #sql???? ?? ???
        use_sql_comments: true #sql? ?? ???
    defer-datasource-initialization: true #data.sql? ???? Hibernate? ?? ??? ???? ??? ??
  sql:
    init:
      mode: always # ?? ??????? sql ????? ?????.